fix documentation
cedricdelpoux/react-svg-piechart pull request #7
Opened 2017-04-06 09:37 UTC by rle-mino

2017-04-10 12:14 UTC, cedricdelpoux requested changes

2017-04-10 12:14 UTC, xuopled commented on README.md
> +import React, { Component } from 'react';
Remove semicolon please

2017-04-10 12:14 UTC, xuopled commented on README.md
> +import PieChart from 'react-svg-piechart';
Remove semicolon please

2017-04-10 12:15 UTC, xuopled commented
Thank you for this PR. Remove the two semicolons please and I will merge it.

2017-04-10 16:41 UTC, rle-mino commented
Done ! Thank you

2017-04-10 16:43 UTC, cedricdelpoux requested changes

2017-04-10 16:43 UTC, xuopled commented on README.md
> +  handleMouseEnterOnSector = (sector) => this.setState({ expandedSector: sector });
I'm sorry but you just add semicolons here

2017-04-10 16:43 UTC, xuopled commented on README.md
> +    const { expandedSector } = this.state;
and here

2017-04-10 16:44 UTC, xuopled commented
One semicolons removed, could you squash yours commits into one ? Thank you

2017-04-10 17:38 UTC, rle-mino commented
Sorry, done !

2017-04-10 23:34 UTC, rle-mino commented
Ok definitely, I'm sorry, this time should be the good one

2017-04-11 12:13 UTC, merged

2017-04-11 12:13 UTC, xuopled commented
Thank you for your help